Tweak config to support HMR
nextcloud/webpack-vue-config pull request #107
Opened 2021-04-28 08:57 UTC by artonge

Tweak config to support hot module reloading.

2021-04-28 10:07 UTC, skjnldsv commented on webpack.js
> +		publicPath: path.join('/apps/', path.join(appName, '/js/')),
So it would only works with the apps folder, right?
What if it's in `apps2` or `custom_apps`?

Or is it a specific alias?

2021-04-28 10:11 UTC, juliushaertl commented on webpack.js
> +		publicPath: path.join('/apps/', path.join(appName, '/js/')),
I'm wondering how that public path is actually picked up as we tend to always overwrite it at runtime with https://webpack.js.org/guides/public-path/#on-the-fly

2021-04-28 10:16 UTC, artonge commented on webpack.js
> +		publicPath: path.join('/apps/', path.join(appName, '/js/')),
You are correct, this only works for apps in the `apps` folder. Also this will not work for core apps, so this is mandatory. I should be able to guess the parent folder.

Thanks for the feedback.

2021-04-28 10:17 UTC, artonge commented on webpack.js
> +		publicPath: path.join('/apps/', path.join(appName, '/js/')),
@juliushaertl can you provided an example of that ?

2021-04-28 11:24 UTC, skjnldsv commented on webpack.js
> +		publicPath: path.join('/apps/', path.join(appName, '/js/')),
@artonge we use it for dynamic import https://github.com/nextcloud/viewer/blob/7be9f861e71f3ac0ddcb6da08fa189361cb7c8ae/src/main.js#L43

2021-04-28 12:00 UTC, artonge commented on webpack.js
> +		publicPath: path.join('/apps/', path.join(appName, '/js/')),
In your example, the shared webpack config would set the public path to `/apps/viewer/js/` and your main.js would override it with the same value (I think). So it would not change anything, beside allowing you to remove this line.

I think the old `publicPath` that was set to `/js/` was not useful to anything.

2021-04-28 14:36 UTC, skjnldsv commented on webpack.js
> +		publicPath: path.join('/apps/', path.join(appName, '/js/')),
Not if the app is installed somewhere else. Like in `/apps2`

2021-04-28 14:36 UTC, skjnldsv commented on webpack.js
> +		publicPath: path.join('/apps/', path.join(appName, '/js/')),
> I think the old `publicPath` that was set to `/js/` was not useful to anything.

Indeed :stuck_out_tongue_closed_eyes:

2021-04-28 14:38 UTC, artonge commented on webpack.js
> +		publicPath: path.join('/apps/', path.join(appName, '/js/')),
> Not if the app is installed somewhere else. Like in /apps2

I am working on a solution :wink:

2021-04-28 20:47 UTC, raimund-schluessler commented on package.json
> -		"@babel/core": "^7.13.10",
Why are all these dependency updates in here?

2021-04-29 08:15 UTC, artonge commented on package.json
> -		"@babel/core": "^7.13.10",
I wasn't sure about that one and wanted to discuss it. I routinely updated the dependencies, but as they are peer dependencies, it will probably break thing or at least display unnecessary warnings for the users of this module.

Should I revert this change ?

2021-04-29 09:43 UTC, skjnldsv commented on package.json
> -		"@babel/core": "^7.13.10",
Yes, this pr should not require any deps update :)
We try our best to not mix unrelated changes with the pull requests.

2021-04-29 10:09 UTC, artonge commented
This should be ready to test.

Don't forget to download and enable to [HMREnabler](https://github.com/nextcloud/hmr_enabler) app for the server.
You will also have to add this new comand in your `package.json`:

```json
"serve": "NODE_ENV=development webpack serve --progress --config webpack.js",
```

2021-05-03 13:33 UTC, skjnldsv commented on README.md
> +__webpack_public_path__ = generateFilePath('viewer', '', 'js/')
```suggestion
__webpack_public_path__ = generateFilePath(appName, '', 'js/')
```

2021-05-03 13:34 UTC, skjnldsv requested changes

2021-05-03 13:34 UTC, skjnldsv commented on README.md
> +- Add the following line in your Vue app entry file so Webpack knows where to fetch updates, [see this example](https://github.com/nextcloud/viewer/blob/7be9f861e71f3ac0ddcb6da08fa189361cb7c8ae/src/m
Ideally this should link the app-tutorial, not a specific repo :wink:

2021-05-03 14:43 UTC, skjnldsv commented on webpack.js
> +	target: 'web',
can be omitted as default is 'web'

2021-05-03 14:45 UTC, artonge commented on webpack.js
> +	target: 'web',
Sadly no:

> Set the target to web (needed because of that: webpack/webpack-dev-server#2758).

2021-05-03 14:49 UTC, skjnldsv commented on webpack.js
> +	target: 'web',
Tss tss webpack! Their docs is outdated then, good catch! :rocket: :hugs:

2021-05-03 16:05 UTC, artonge commented on README.md
> +- Add the following line in your Vue app entry file so Webpack knows where to fetch updates, [see this example](https://github.com/nextcloud/viewer/blob/7be9f861e71f3ac0ddcb6da08fa189361cb7c8ae/src/m
I linked to the app-tutorial's `main.js` which does no contains the example yet, but will after this is merged.

2021-05-03 16:07 UTC, artonge commented on webpack.js
> +	target: 'web',
It is more of a bug. It should be fixed when `webpack-dev-server@4` is released.

2021-05-03 16:19 UTC, skjnldsv commented
This is still missing the `webpack-dev-server` deps, no?

2021-05-03 16:27 UTC, skjnldsv reviewed
It seems to be fetching https for me, because my dev instance have a certificate. But the webpack serve only listens to http :thinking: 

Setting up `https: false` in the DevServer does not works
https://webpack.js.org/configuration/dev-server/#devserverhttps

2021-05-03 16:27 UTC, artonge commented
Yes,I wasn't sure it was necessary to add it as Webpack install it dynamically on the first `webpack serve` call and adding it in this `package.json` won't prevent the need to install it manually.

2021-05-03 16:35 UTC, artonge commented
> It seems to be fetching https for me, because my dev instance have a certificate. But the webpack serve only listens to http thinking
> 
> Setting up `https: false` in the DevServer does not works
> https://webpack.js.org/configuration/dev-server/#devserverhttps

It might be due to the `__webpack_public_path__` override. The `generateFilePath` function will generate an URL with `https`.

2021-05-03 17:55 UTC, skjnldsv commented
> Yes,I wasn't sure it was necessary to add it as Webpack install it dynamically on the first `webpack serve` call and adding it in this `package.json` won't prevent the need to install it manually.

Since this is a required dep for this lib to work with 100% of its features, we need it as dep and peer dep :)

2021-05-04 11:55 UTC, skjnldsv commented
I think it's because my dev setup have a domain, the HMR_enabler doesn't fix the CSP for same-domain request, no?

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://localhost:3000/sockjs-node/info?t=1620129348916. (Reason: CORS request did not succeed).`

2021-05-04 12:48 UTC, artonge commented
> I think it's because my dev setup have a domain, the HMR_enabler doesn't fix the CSP for same-domain request, no?

The problem here is that the Webpack devServer block requests coming from other web pages. This prevent say `pirate.com` to access the webpack devServer and do bad things.

The solution is to:
- either set `devServer.disableHostCheck` to `true`, which is insecure.
- or set `devServer.allowedHosts` to `['domain1', 'domain2', '...']`, and try to list all domains used by the developers, which will probably always be incomplete, but maybe we can agree on a set of domains. And we can't do stuff like '*.localhost'.

We could also use a shell environment variable by setting `devServer.allowedHosts` to `[process.env.TEST_DOMAIN]` so everyone can do ` TEST_DOMAIN='nextcloud.test' make serve-js`, but maybe that bring to much complexity.

2021-05-04 13:16 UTC, skjnldsv commented
> * either set `devServer.disableHostCheck` to `true`, which is insecure.

Tried this, did not work :/

2021-05-04 16:15 UTC, artonge commented
> > * either set `devServer.disableHostCheck` to `true`, which is insecure.
> 
> Tried this, did not work :/

So, I was able to reproduce your error. It was due to Webpack using https to communicate but as it wasn't listening with https enabled, the requests failed. I pushed a solution to force Webpack to use http.

The other problem I reported still stand as you will notice. The current solution is to set an environment variable when running the dev server, but I don't think that is the best.

2021-05-05 16:57 UTC, juliushaertl commented on webpack.js
> +				process.env.NEXTCLOUD_DOMAIN || 'nextcloud.localhost'
I think we could just assume `localhost` for that and if the developer is using a different hostname this can be passed through the command line arguments like:

```
npm run serve -- --allowed-hosts .host.com
```

No matter what, we should document this at the README ;)

2021-05-05 16:59 UTC, juliushaertl reviewed
Small comment regarding the environment variable, otherwise this works fine for me in deck with a limitation:

There seems to be an issue with multiple entrypoints that might be loaded from the same app that runs in hot reload mode which then causes the update to be not properly detected, but I'd consider that not as a blocker for now.

Really nice so far :+1:

2021-05-05 17:26 UTC, artonge commented on webpack.js
> +				process.env.NEXTCLOUD_DOMAIN || 'nextcloud.localhost'
Much better, thanks

2021-05-10 08:34 UTC, juliushaertl approved these changes

2021-05-10 13:38 UTC, skjnldsv approved these changes

2021-05-10 13:38 UTC, merged